# Generated by Django 3.2 on 2024-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240903_1934'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_not_me',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, username='me'), name='username_not_me'),
        ),
    ]
