# Generated by Django 3.2 on 2024-09-07 18:02

import django.contrib.auth.validators
from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240907_1945'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_not_me',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.utils.validate_username_not_me], verbose_name='Никнейм'),
        ),
    ]
